### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by konradre** [daniabib/ComfyUI_ProPainter_Nodes#11]
```
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes\__init__.py", line 1, in <module>
    from .propainter_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes\propainter_nodes.py", line 4, in <module>
    from .propainter_inference import (
  File "D:\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes\propainter_inference.py", line 10, in <module>
    from .model.recurrent_flow_completion import (
  File "D:\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes\model\recurrent_flow_completion.py", line 7, in <module>
    from .misc import constant_init
  File "D:\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes\model\misc.py", line 67, in <module>
    re.findall(
IndexError: list index out of range
```

**Comment by konradre** [comment]
Fixed by using the fix in https://github.com/daniabib/ComfyUI_ProPainter_Nodes/issues/9
